### PR TITLE
Issue302 native execution

### LINKED ISSUE #302: BadImageFormatException building solution with unmanaged projects
I have a solution with both managed and native projects. NUnit adapter seems to try to load a native DLL and fails whenever I rebuild the project. You can see the solution here: [Log4JDash](/MaxKot/Log4JDash/).

Error message (Log4JParserC.dll is an unmanaged library and Log4JDash.exe is an unmanaged application):

> ------ Discover test started ------
> NUnit Adapter 3.7.0.0: Test discovery starting
> Assembly contains no NUnit 3.0 tests: D:\develop\Log4JDash\src\Log4JDash.Web\bin\Log4JDash.Web.dll
> Assembly contains no NUnit 3.0 tests: D:\develop\Log4JDash\src\Log4JParserDashNet\bin\x86\Release\Log4JParserDashNet.exe
> Assembly contains no NUnit 3.0 tests: D:\develop\Log4JDash\src\Log4JParserNet\bin\x86\Release\Log4JParserNet.dll
> Error: Unable to get runner for this assembly. Check installation, including any extensions.
> BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
> Assembly not supported: D:\develop\Log4JDash\src\Release\Log4JDash.exe
> Error: Unable to get runner for this assembly. Check installation, including any extensions.
> BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
> Assembly not supported: D:\develop\Log4JDash\src\Release\Log4JParserC.dll
> NUnit Adapter 3.7.0.0: Test discovery complete
> ========== Discover test finished: 27 found (0:00:00,3920224) ==========

Visual Studio info:

> Microsoft Visual Studio Community 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01055

Similar issue is [also reported](/nunit/nunit3-vs-adapter/issues/231#issuecomment-263929798) by @anttirt:

> I have the same issue as MaxKot; it's related to #248.
> 
> The issue is otherwise benign except that the `Error` log causes focus to switch to the `Tests` section in the output window after every build of the solution, which can be very annoying. :)
> 
> The NUnit runner _should_ somehow detect that a project is a native code project and skip it without emitting an error message, but I don't know if there's an API for that off the top of my head. The built in test discoverer for Visual Studio has the following to say:
> 
>```
> Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> my_native_project.exe is built for Framework None and Platform X64.
>```
> 
> So perhaps skipping "assemblies" with `Framework = None` would do the trick?
> 
> I don't have time to experiment with this right now but may take a look at it later this week.

### PR DESCRIPTION
**Pull request by OskiKervinen-MF**
Merge request !369 only fixes #302 for test discovery, not for test execution. There you still get an error when a native binary is given to NUnit, because the BadFormatException is wrapped in a NUnitEngineException and that case was not checked in the execution code path.

Added a test to detect this and a fix for the problem.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
Looks good to me too, just want to create a duplicate issue to connect this to, since the #302 is closed already.  I'll do this today, merge it later today too.

File: src/NUnitTestAdapter/NUnit3TestExecutor.cs [hunk 1]
```diff
@@ -299,6 +299,15 @@ private void RunAssembly(string assemblyPath, TestFilter filter)
...
                 TestLog.Warning("   Assembly not supported: " + assemblyPath);
             }
+            catch( NUnitEngineException e )
+            {
+                if( e.InnerException is BadImageFormatException )
+                {
+                    // we skip the native c++ binaries that we don't support.
+                    TestLog.Warning( "   Assembly not supported: " + assemblyPath );
+                }
+                throw;
```
Comment (jnm2) [inline src/NUnitTestAdapter/NUnit3TestExecutor.cs:309]: This `throw;` means that NUnitEngineExceptions are no longer handled at all. They used to be handled in the `catch (Exception)` section below.

Comment (jnm2) [reply src/NUnitTestAdapter/NUnit3TestExecutor.cs:309]: Fixed by #804
