### PR TITLE
Fix navigation data retrieval for methods defined in a base class

### LINKED ISSUE #163: Inheriting test methods from abstract base test fixutures emits "No source data found for..." warning.
A couple of weeks ago I ran into a scenario that can be stripped down to something like this

    abstract class BaseFixture
    {
        [NUnit.Framework.Test]
        public void RunTest()
        {
        }
    }

    class DerivedTester : BaseFixture
    {
    }
So in essence, I'm deriving a class from an abstract test fixture that has a test method. The test adapter successfully recognizes a test method in the derived classed `DerivedTester`, but I get a message in the output window, Tests channel reading

    No source data found for InheritedTests.DerivedTester.RunTest
The above code was inside a namespace called `InheritedTests`, hence the namespace prefix. This symptom has been touched upon in nunit/nunit-vs-adapter#6 and nunit/nunit#1080, albeit while using generics somehow. My code here doesn't use generics; the message appeared all the same.

### PR DESCRIPTION
**Pull request by CharliePoole**
Fixes #163 

This fix can be left in even after the framework itself is fixed to return the correct declaring class name for tests defined in a base class. The new code only comes into play if the navigation data can't be retrieved in the normal way.

### CODE REVIEW

**Comment by CharliePoole** [comment]
@MSK61 This is inspired by your code but somewhat simplified. Feel free to review the PR.

File: src/NUnitTestAdapter/Internal/NavigationDataHelper.cs [hunk 1]
```diff
@@ -17,6 +17,20 @@ public void LoadAssembly(string assemblyName)
...
+            if (type != null)
+            {
+                var method = type.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
+                if (method != null)
+                    return method.DeclaringType.FullName;
+            }
+
+            return className;
+        }
+
```
Comment (MSK61) [inline src/NUnitTestAdapter/Internal/NavigationDataHelper.cs]: I see no problem in duplicating the lookup code here(in GetDefiningClassName) with the old one GetClassNameForAsyncMethod as they have different enough matching criteria.

File: src/NUnitTestAdapter/TestConverter.cs [hunk 2]
```diff
@@ -159,14 +159,24 @@ public DiaNavigationData GetNavigationData(string className, string methodName)
         {
             if (this.DiaSession == null) return null;
 
+            // First try using the class and method names provided directly
             var navData = DiaSession.GetNavigationData(className, methodName);
```
Comment (MSK61) [inline src/NUnitTestAdapter/TestConverter.cs]: If `NavigationDataHelper` is not `null` and the method is defined in a base class this statement will always return `null` navigation data and later flow will proceed through if `(NavigationDataHelper != null)` anyway; I would suggest that you try with the provided class name only when `NavigationDataHelper` is `null`. I'm assuming that `NavigationDataHelper.GetDefiningClassName` call isn't so expensive anyway(unless you know otherwise).

Comment (CharliePoole) [inline src/NUnitTestAdapter/TestConverter.cs]: This is true so long as you are not creating the AppDomain unnecessarily and it's already created if NavigationDataHelper is non null. I thought about doing what you suggest but i was afraid the code would be hard to read. Let me see if I can change the names of some variables and properties so it is not confusing.

File: src/NUnitTestAdapter/Internal/NavigationDataHelper.cs (hunk 1 above)
Comment (CharliePoole) [inline src/NUnitTestAdapter/Internal/NavigationDataHelper.cs]: We need both methods called in this order because you could have an async method defined in a base class.

File: src/NUnitTestAdapterTests/NavigationDataTests.cs [hunk 3]
```diff
@@ -47,6 +47,7 @@ public void TearDown()
         [TestCase("+GenericFixture`2", "Matches", 116, 117, 117, 118)]
         [TestCase("+GenericFixture`2+DoublyNested", "WriteBoth", 132, 133, 134, 134)]
         [TestCase("+GenericFixture`2+DoublyNested`1", "WriteAllThree", 151, 152, 153, 153)]
+        [TestCase("+DerivedClass", "EmptyMethod_ThreeLines", 160, 161, 161, 161)]
```
Comment (rprouse) [inline src/NUnitTestAdapterTests/NavigationDataTests.cs]: What am I missing here? In the code in `NavigationTestData`, `DerivedClass` does not derive from `BaseClass`. How is `EmptyMethod_ThreeLines` being found, especially since it is named differently?

Comment (CharliePoole) [inline src/NUnitTestAdapterTests/NavigationDataTests.cs]: Well that explains things!  

It's not being caught in the CI build or my local batch runs because we exclude the navigation tests. I've been using the test in the demo app to verify that it works.

I'll update this.

File: src/NUnitTestAdapter/Internal/NavigationDataHelper.cs (hunk 1 above)
Comment (CharliePoole) [inline src/NUnitTestAdapter/Internal/NavigationDataHelper.cs]: I duplicated the code to call GetMethods and apply a selection to it - it's actually needed if there is more than one method.

File: src/NUnitTestAdapter/TestConverter.cs (hunk 2 above)
Comment (CharliePoole) [inline src/NUnitTestAdapter/TestConverter.cs]: I decided not to make this efficiency improvement. If we end up replacing the use of DiaSession with Mono.Cecil, no AppDomain will be needed. if we don't we can come back to this.

File: src/NUnitTestAdapterTests/NavigationDataTests.cs (hunk 3 above)
Comment (CharliePoole) [inline src/NUnitTestAdapterTests/NavigationDataTests.cs]: Fixed this.

Comment (rprouse) [inline src/NUnitTestAdapterTests/NavigationDataTests.cs]: @CharliePoole I see you updated `DerivedClass` but the method is still `EmptyMethod_ThreeLines` here and `EmptyMethodThreeLines` in `BaseClass`. That is incorrect isn't it?

Comment (CharliePoole) [inline src/NUnitTestAdapterTests/NavigationDataTests.cs]: I have a mental block for this test I guess. Fixed.

**Comment by CharliePoole** [comment]
I'm going ahead and merging at this point. There are some cleanup and efficiency steps I would take except that we may be phasing out this code in short order - if the use of Mono.Cecil to replace it works out. This will go into the 3.2 release now and I'll replace or revisit it for the 3.4 release.
